version: '3'
services:
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    expose:
      - 27017
    volumes:
      - ./chromekdbx_db-data/_data:/data/db

  node:
    build: .
    ports:
      - "444:444"
    volumes:
      - .:/opt/app
    working_dir: /opt/app
