version: '3'
services:
  mongo:
    build: ./src/js/sync_server
    ports:
      - "27017:27017"
    expose:
      - 27017
    volumes:
      - db-data:/data/db

  node:
    build: .
    ports:
      - "9223:9223"
      - "444:444"
    volumes:
      - .:/opt/app

volumes:
  db-data: